# Computational resources 
cores: 16 

# Paths 
data_folder: "/home/renku/work/epfl-altshuler/GlobalAlpineSoilMicrobiome/data" 
output_dir: "/home/renku/work/epfl-altshuler/GlobalAlpineSoilMicrobiome/results"
