channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base>=4.3
  - r-tidyverse
  - r-maps
  - r-raster
  - r-terra
  - r-data.table
  - r-sf
  - r-vegan
  - r-geosphere
  - r-slam
  - r-rbiom
  - bioconductor-phyloseq
